### ISSUE TITLE
Transition Bot Parrots Back Anything I Type and No Bytes Awarded w/ Signed and Confirmed BTC Wallet

### ISSUE THREAD

**Issue by BigTurboCrypto** [byteball/byteball#104]
Everything was working fine most of the day on May 10th, I had the transition bot confirming that I had a signed BTC wallet w/ BTC in it ready for the full moon distribution (see bot message below), then later that evening the bot stopped answering and began parroting back anything I typed into the chat box and the app began crashing. I have downloaded the update (1.8.3) today but the bot is still just sending the same message I type to it, back to me and I show no bytes awarded for having BTC in my wallet for the entire day of May 10th. 

**************************************************************************************
Your current linked Bitcoin address is (omitted).

Please make sure that (omitted) is indeed your address and move all your coins to this address. You receive 62.5 MB and 131,943,750 blackbytes for each 1 BTC of the total balance of this Bitcoin address on May 10.

Current balance of this address is 3.90840092 BTC.

For the bytes you hold on May 10 you receive 0.1 new byte for each 1 byte of your balance, even if your bytes are not on linked Byteball addresses.

You also receive 0.21111 blackbytes for each 1 byte of your balance on the linked Byteball address, which currently is:
(omitted): 0 GB.

Move your bytes to the linked address in order to maximize the amount of blackbytes you receive.
**************************************************************************************

**Comment by tonyofbyteball** [comment]
Upgrade to 1.8.5 and check your balance.
During the distribution, the seat of the transition bot was taken by the distribution bot.  Now the transition bot is back, you can chat with it again.
