### ISSUE TITLE
Android v1.8.3 hash #8732f2d seed & backup clusterfu

### ISSUE THREAD

**Issue by TheButterZone** [byteball/byteball#105]
Previous version I was able to get my seed and I copied it down. 1.83 says "Wallet seed not available" & "Recovery is only available in full wallets."

Full backup takes forever to complete, finally does (without prompting for a save location), I go to restore, hit "Choose File" and the button flickers but remains "No file chosen" with no dialog box to pick a file explorer/directory.

Same behavior after a force stop and relaunch.

ETA: I did a system-wide file search and found ByteballBackup####....encrypted, so I backed up the backup.

**Comment by xJeneKx** [comment]
@TheButterZone What is your device and version android?

**Comment by TheButterZone** [comment]
GT-N5110 4.4.2

**Comment by TheButterZone** [comment]
Ok so import now opens the file explorer, but there are still the issues of 
1) the full backup location not being choosable or even pointed to after the encryption is complete
2) "Wallet seed not available" & "Recovery is only available in full wallets."
