### ISSUE TITLE
Uncaught exception: ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by Quark-Fusion** [byteball/byteball#11]
After i tried to send 1 BB to myself on multisig 2 of 3 wallet second device which should authorize transaction raises this error on every start and closes after pressing ok button.

**Comment by tonyofbyteball** [comment]
Will be fixed in the next release
https://github.com/byteball/byteballcore/commit/2d7df7244f101518698c83ccf5191e9cfffe2041

**Comment by tonyofbyteball** [comment]
Fixed in 1.1.0
