### ISSUE TITLE
what's the meaning of Error 1

### ISSUE THREAD

**Issue by lipengda** [byteball/byteball#114]
when i build iOS,message:
=======================================================
localhost:byteball lipengda$ make ios-debug
cordova/build.sh IOS --dbgjs
* Checking dependencies...
Build directory is /Users/lipengda/byteball/byteball/cordova
Project directory is /Users/lipengda/byteball/byteball/cordova/../../byteballbuilds/project-IOS
* Generating byteball bundle (debug js)...
Running "nggettext_compile:all" (nggettext_compile) task

Running "exec:version" (exec) task
v1.8.5 #370f8e9

Running "concat:angular" (concat) task

Running "concat:js" (concat) task

Running "concat:css" (concat) task

Running "concat:foundation" (concat) task

Running "copy:icons" (copy) task
Copied 5 files

Running "browserify:dist" (browserify) task
>> Bundle public/byteball.js created.

Running "uglify:prod" (uglify) task
File public/byteball.js created: 4.35 MB → 2.38 MB
File public/angular.js created: 2.51 MB → 872.3 kB
>> 2 files created.

Done.
* Copying files...
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
* ERROR. Exiting...
make: *** [ios-debug] Error 1
localhost:byteball lipengda$ 
=======================================================
look forward to your reply!

**Comment by tonyofbyteball** [comment]
Try creating a symlink in your ../byteballbuilds from ios to project-IOS.
