### ISSUE TITLE
Move user folder

### ISSUE THREAD

**Issue by zimmah** [byteball/byteball#117]
As usual, Byteball stores a lot of data in the C:\Users folder.    

I don't want to store a lot of random data in my C:\Users folder because my C:\ drive is small and reserved for my OS.      
   
How do I move this to a different drive?

**Comment by tonyofbyteball** [comment]
It is common practice for apps to store their data in the user's home directory, Byteball is not alone here.  Google for tips about changing the default location of the user folder, or create a symlink (if it exists on Windows)

**Comment by zimmah** [comment]
Yes but not gigabytes of data, that's just lazy programming.   
Most apps allow you to choose where you store most of the data, and you shouldn't be forced to store gigabytes of data in your User folder, that's not what it's for.

**Comment by JulianTosh** [comment]
Zimmah, you should be running the byteball wallet (espcially a full wallet) as a separate, isolated user, with its home directory in a different volume if you need the HD space. The overridding factor is keeping the application isolated from software that doesn't need access to is, or visa versa. This solves both your wallet security and space issues.

Some tips to use the wallet in a different non-privileged context, use windows 'runas' or in linux, use su - byteball and export DISPLAY=:0.0 in the shell.

**Comment by zimmah** [comment]
@JulianTosh thank you for the tip. I will try to set that up at some other time when I have the time to take a closer look at it.
