### ISSUE TITLE
Can you give some byte for a try?

### ISSUE THREAD

**Issue by soliury** [byteball/byteball#14]
This is my address: QR7Y7E6UVAM7JIHVPSA7TH6T5SCTDZJJ

**Comment by hyeongwoojeong** [comment]
QR7Y7E6UVAM7JIHVPSA7TH6T5SCTDZJJ

**Comment by hyeongwoojeong** [comment]
감사합니다

**Comment by amacar** [comment]
For trying you can use test network, otherwise stop begging and just buy some while they are cheap. YOu can buy them here right now: https://cryptox.pl
