### ISSUE TITLE
Sending while amounts pending results in empty transaction

### ISSUE THREAD

**Issue by CorePrime95** [byteball/byteball#145]
Send 1 GB to empty wallet A. While wallet A shows that the 1 GB are pending, you can already do a send to wallet B. This however produces a transaction with 0 GB from A to B.

**Comment by tonyofbyteball** [comment]
example of such 0 GB tx on the explorer?

**Comment by CorePrime95** [comment]
Its not totally 0 byte, but a very small number of byte so it shows up as 0 GB

UWriw32HXibZpJhjWTTLV9EwgOAJOVywtvcW/LlxrwQ=

![grafik](https://user-images.githubusercontent.com/29467787/27397001-2626b68a-56b5-11e7-9ea9-5a75581f6bdd.png)

**Comment by tonyofbyteball** [comment]
Looks like the wallet was not empty because this tx spent an input that was not 1 GB.  Please list the exact steps to reproduce.

**Comment by tonyofbyteball** [comment]
Fixed https://github.com/byteball/byteballcore/commit/64cf3a44b29c19358e58ddb100cf9053dd48b289
