### ISSUE TITLE
Add byteball to my GitHub.com

### ISSUE THREAD

**Issue by Zinasimab** [byteball/byteball#166]
I want byteball to be added to my GitHub account

**Comment by thedavidmeister** [comment]
@Zinasimab just click "fork" in the top right hand corner and you will get your own copy on your github account.

<img width="145" alt="screen shot 2017-07-07 at 11 12 52 pm" src="https://user-images.githubusercontent.com/629710/27959213-ea4bddc2-6369-11e7-87c7-fec90d60c48c.png">
