### ISSUE TITLE
sqlite temporary files don't seem to be getting cleaned up properly on wallet shutdown

### ISSUE THREAD

**Issue by thedavidmeister** [byteball/byteball#169]
When I open the byteball app 2 sqlite temporary files are created:

- `byteball-light.sqlite-shm`
- `byteball-light.sqlite-wal`

According to https://sqlite.org/tempfiles.html both of these files should be deleted when sqlite shuts down correctly.

However, when I quit the byteball wallet these two files remain. Opening/closing the `.sqlite` file in another application such as http://sqlitebrowser.org/ seems to correctly cleanup these files, so the issue seems to be with byteball.

**Comment by tonyofbyteball** [comment]
Not an issue, sqlite correctly finds these files on next launch.

**Comment by thedavidmeister** [comment]
@tonyofbyteball from linked docs:

```
However, if the last connection does not shutdown cleanly, the WAL file will remain in the filesystem and will be automatically cleaned up the next time the database is opened.
```

I get that it is cleaned up on next open but is it really OK to not have clean shutdown?

**Comment by tonyofbyteball** [comment]
It is OK.
