### ISSUE TITLE
TypeError: Cannot read property 'initDeviceProperties' of undefined; cause: undefined

### ISSUE THREAD

**Issue by gagna** [byteball/byteball#173]
I got this error after try to restore wallet from seed. Now every time I lauch wallet It start and stops at that screen. If I hit ok wallet close.

Wallet seed is from BB wallet on my lost android phone, I tried to restore it on desktop app for Win10

![bb](https://user-images.githubusercontent.com/7458860/27985526-93d647a6-63ec-11e7-9c90-672ce26ed298.jpg)

![bb3](https://user-images.githubusercontent.com/7458860/27985525-8f77130c-63ec-11e7-8d21-91095e778843.jpg)

**Comment by tonyofbyteball** [comment]
Restore from seed fixed in 1.9.2
