### ISSUE TITLE
Transfer not received

### ISSUE THREAD

**Issue by samrajyacoin** [byteball/byteball#174]
downloaded wallet for mac os. right now wallet is syncing at 2/23/2017 12:59AM. transferred GBYTE from exchange to this wallet address but not received. Is it because of the sync or ....? please advise

**Comment by tonyofbyteball** [comment]
Yes, because of sync, will be visible when your sync reaches the transfer date.

**Comment by samrajyacoin** [comment]
Thank you! sync completed and coins received.
