### ISSUE TITLE
SQLITE Error after computercrash

### ISSUE THREAD

**Issue by Espo02** [byteball/byteball#180]
Hello

My Byteball instance doesn't work after an Power failure. What can I do to repair this database?
Thx for Help

![byteball sqlite](https://user-images.githubusercontent.com/17567386/28216507-3ef77d52-68b2-11e7-9920-c7614dbe98ec.PNG)

**Comment by KolesnikConstantin** [comment]
There is the same issue on another wallet. Can you help?

**Comment by fabi2803** [comment]
Had the same when I closed my Laptop while syncing a few times. Waited a few days and then it was okay again.
But today it came with no reason. I don't know if it is luck but my syncing is at 7/14/17 12:02 AM.

**Comment by tonyofbyteball** [comment]
Preparing a new release to fix this bug.  Not related to power failure.

**Comment by fabi2803** [comment]
It's working for me again, thank you.

**Comment by tonyofbyteball** [comment]
fixed in 1.9.2
