### ISSUE TITLE
Wallet stuck with uncaught exception: Error  version 1.9.2

### ISSUE THREAD

**Issue by lijoe408** [byteball/byteball#184]
Running full wallet 1.9.1. which got stuck at 0%.  I upgraded to 1.9.2 and now everytime i open the wallet it gives the following.

Uncaught exception: Error: known bad gf34NrX7vYGSmpvespTReJoU/ayyDQXDVKo+ez4XlUE=: unit X/zX8WVZFMPngqZD86o8Z/sLJB2JE30UqGF3Fj8BB+o= does not exist (catching up)

**Comment by Michail1** [comment]
Was this not caused by a corrupt sql DB which you were able to recover from either a backup or redownload (resync) of the DB?

**Comment by tonyofbyteball** [comment]
Looks like you are still on 1.9.1.  The latest version is 1.9.3, please upgrade.
