### ISSUE TITLE
Uncaught exception: Error: Error: SQLITE_CONSTRAINT:FOREIGN KEY constraint failed INSERT INTO unit_authors(unit, address, definition_chash) values (?,?,?)

### ISSUE THREAD

**Issue by barryhi** [byteball/byteball#185]
Please help

**Comment by Sahree** [comment]
Have the same problem after the "update".
Uncaught exception: Error: Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed

**Comment by barryhi** [comment]
Problem resolved after upgraded to 1.9.3

Thanks

**Comment by tonyofbyteball** [comment]
This and a few other bugs fixed in 1.9.3 or before.
