### ISSUE TITLE
get "known bad" error on 1.9.3 byteball wallet

### ISSUE THREAD

**Issue by pxrunes** [byteball/byteball#189]
here is a log from my payment attempt:
could this also be a problem of the contract?
---------------------------------------

sending payment in base
outbound peers: wss://byteball.org/bb
SENDING ["request",{"command":"light/get_parents_and_last_ball_and_witness_list_unit","params":{"witnesses":["BVVJ2K7ENPZZ3VYZFWQWK7ISPCATFIW3","DJMMI5JYA5BWQYSXDPRZJVLW3UGL3GJS","FOPUBEUPBC6YLIQDLKL6EW775BMV7YOH","GFK3RDAPQLLNCMQEVGGD2KCPZTLSG3HN","H5EZTQE7ABFH27AUDTQFMZIALANK6RBG","I2ADHGP4HL6J37NQAD73J7E5SKFIXJOT","JEDZYC2HMGDBIDQKG3XSTXUSHMCBK725","JPQKPRI5FMTQRJF4ZZMYZYDQVRD55OTC","OYW2XTDKSNKGSEZ27LMGNOPJSYIXHBHC","S7N5FE42F6ONPNDQLCF64E2MGFYKQR2I","TKT4UESIKTTRALRRLWS4SENSTJX6ODCW","UENJPVZ7HVHM6QGVGT6MWOJGGRTUTJXQ"]},"tag":"0cKYzeG4R688aC+BTqkHMrC4QAiytyqjlyMIKd7kmOY="}] to wss://byteball.org/bb
RECEIVED ["response",{"tag":"0cKYzeG4R688aC+BTqkHMrC4QAiytyqjlyMIKd7kmOY=","response":{"parent_units":["Dj9CQ0MfE4EEqhlLpHOF6CtAa44wZLzFLaKtB2B6W+8="],"last_stable_mc_ball":"5I2vit+WsQMHB/lBjWjVjUpKA3qzYMOF5xMokjyoWy0=","last_stable_mc_ball_unit":"jfHJWhoy22leprs+m5c7GzcsepGTYoZkPm83rCbkmPY=","last_stable_mc_ball_mci":799776,"witness_list_unit":"oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E="}}] from wss://byteball.org/bb
lock acquired ["c-DYKJLDOG22WJZI5GKXE2FJGUWJIV7HRB", "c-ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ"]
pick coins null amount Infinity
DYKJLDOG22WJZI5GKXE2FJGUWJIV7HRB headers_commission: got only 10000 out of required Infinity
DYKJLDOG22WJZI5GKXE2FJGUWJIV7HRB witnessing: got only 10000 out of required Infinity
inputs increased payload by 60
{ unit: 
   { version: '1.0',
     alt: '1',
     messages: 
      [ { app: 'payment',
          payload_location: 'inline',
          payload_hash: 'RhmBF9h1OC3YGuDkYW8xUBNEEgVP1MXakE5GDvzqJZA=',
          payload: 
           { outputs: [ { address: 'A5VKYY6JBI4WVZTMJAJY7IBJW3LXQSHA', amount: 9082 } ],
             inputs: 
              [ { unit: 'bpbNQxSNX9vLVlW1hPHsQx5dQ+4oyGNnLIkBh/2wHjk=',
                  message_index: 0,
                  output_index: 1 } ] } } ],
     authors: 
      [ { address: 'DYKJLDOG22WJZI5GKXE2FJGUWJIV7HRB',
          authentifiers: { 'r.1.0': 'GRVngJXy0JQQAX1GES2a9a1osV+Nbcl9no/RWTcVhuAcDnxxcDW8QI7EIZ5T4RvNgdg6C7bNgGz2pxU7c9Ipiw==' },
          definition: 
           [ 'or',
             [ [ 'and',
                 [ [ 'address', '3XEJBQSULFXYVXARJ56AQE7K6O3UBKO5' ],
                   [ 'has',
                     { what: 'output',
                       asset: 'base',
                       amount_at_least: 800000,
                       address: 'ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ' } ] ] ],
               [ 'and',
                 [ [ 'address', 'ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ' ],
                   [ 'in data feed',
                     [ [ 'OPNUXBRSSQQGHKQNEPD2GLWQYEUY5XLD' ],
                       'timestamp',
                       '>',
                       1500812847748 ] ],
                   [ 'not',
                     [ 'has',
                       { what: 'output',
                         asset: 'base',
                         amount_at_least: 800000,
                         address: 'ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ' } ] ] ] ] ] ] },
        { address: 'ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ',
          authentifiers: { r: 'GRVngJXy0JQQAX1GES2a9a1osV+Nbcl9no/RWTcVhuAcDnxxcDW8QI7EIZ5T4RvNgdg6C7bNgGz2pxU7c9Ipiw==' } } ],
     earned_headers_commission_recipients: 
      [ { address: 'A5VKYY6JBI4WVZTMJAJY7IBJW3LXQSHA',
          earned_headers_commission_share: 100 } ],
     parent_units: [ 'Dj9CQ0MfE4EEqhlLpHOF6CtAa44wZLzFLaKtB2B6W+8=' ],
     last_ball: '5I2vit+WsQMHB/lBjWjVjUpKA3qzYMOF5xMokjyoWy0=',
     last_ball_unit: 'jfHJWhoy22leprs+m5c7GzcsepGTYoZkPm83rCbkmPY=',
     witness_list_unit: 'oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=',
     headers_commission: 761,
     payload_commission: 157,
     unit: 'NbbkcXsMO/AM69VD1idGt8kG5oossslJJr8ukGGG4lQ=' } }

validating joint identified by unit NbbkcXsMO/AM69VD1idGt8kG5oossslJJr8ukGGG4lQ=
base asset OK good
posing joint identified by unit NbbkcXsMO/AM69VD1idGt8kG5oossslJJr8ukGGG4lQ= to light vendor
outbound peers: wss://byteball.org/bb
SENDING ["request",{"command":"post_joint","params":{"unit":{"version":"1.0","alt":"1","messages":[{"app":"payment","payload_location":"inline","payload_hash":"RhmBF9h1OC3YGuDkYW8xUBNEEgVP1MXakE5GDvzqJZA=","payload":{"outputs":[{"address":"A5VKYY6JBI4WVZTMJAJY7IBJW3LXQSHA","amount":9082}],"inputs":[{"unit":"bpbNQxSNX9vLVlW1hPHsQx5dQ+4oyGNnLIkBh/2wHjk=","message_index":0,"output_index":1}]}}],"authors":[{"address":"DYKJLDOG22WJZI5GKXE2FJGUWJIV7HRB","authentifiers":{"r.1.0":"GRVngJXy0JQQAX1GES2a9a1osV+Nbcl9no/RWTcVhuAcDnxxcDW8QI7EIZ5T4RvNgdg6C7bNgGz2pxU7c9Ipiw=="},"definition":["or",[["and",[["address","3XEJBQSULFXYVXARJ56AQE7K6O3UBKO5"],["has",{"what":"output","asset":"base","amount_at_least":800000,"address":"ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ"}]]],["and",[["address","ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ"],["in data feed",[["OPNUXBRSSQQGHKQNEPD2GLWQYEUY5XLD"],"timestamp",">",1500812847748]],["not",["has",{"what":"output","asset":"base","amount_at_least":800000,"address":"ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ"}]]]]]]},{"address":"ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ","authentifiers":{"r":"GRVngJXy0JQQAX1GES2a9a1osV+Nbcl9no/RWTcVhuAcDnxxcDW8QI7EIZ5T4RvNgdg6C7bNgGz2pxU7c9Ipiw=="}}],"earned_headers_commission_recipients":[{"address":"A5VKYY6JBI4WVZTMJAJY7IBJW3LXQSHA","earned_headers_commission_share":100}],"parent_units":["Dj9CQ0MfE4EEqhlLpHOF6CtAa44wZLzFLaKtB2B6W+8="],"last_ball":"5I2vit+WsQMHB/lBjWjVjUpKA3qzYMOF5xMokjyoWy0=","last_ball_unit":"jfHJWhoy22leprs+m5c7GzcsepGTYoZkPm83rCbkmPY=","witness_list_unit":"oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E=","headers_commission":761,"payload_commission":157,"unit":"NbbkcXsMO/AM69VD1idGt8kG5oossslJJr8ukGGG4lQ=","timestamp":1500814735}},"tag":"cHOsOc4bsqil2Wyd2NlHJjWOHK6p2zsfWoA+mhf9o/o="}] to wss://byteball.org/bb
RECEIVED ["response",{"tag":"cHOsOc4bsqil2Wyd2NlHJjWOHK6p2zsfWoA+mhf9o/o=","response":{"error":"known bad"}}] from wss://byteball.org/bb
failed to post base payment NbbkcXsMO/AM69VD1idGt8kG5oossslJJr8ukGGG4lQ=
lock released ["c-DYKJLDOG22WJZI5GKXE2FJGUWJIV7HRB", "c-ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ"]
handleQueue 0 items
handleQueue done 0 items
done payment in base, err=known bad
queued jobs: [], locked keys: []
0 incoming connections, 1 outgoing connections, 0 outgoing connections being opened
logging in to hub byteball.org/bb
outbound peers: wss://byteball.org/bb
resending stalled messages
lock acquired ["stalled"]
lock acquired ["private_chains"]
lock acquired ["saved_private"]
0 stalled messages
lock released ["stalled"]
handleQueue 0 items
handleQueue done 0 items
lock released ["private_chains"]
handleQueue 0 items
handleQueue done 0 items
lock released ["saved_private"]
handleQueue 0 items
handleQueue done 0 items
outbound peers: wss://byteball.org/bb
already connected to light vendor

**Comment by tonyofbyteball** [comment]
Most likely, you can't spend this contract.  The first time you try to do it you get a reason why.  If you repeat without any changes, you get "known bad".

I see OPNUXBRSSQQGHKQNEPD2GLWQYEUY5XLD in the contract, it is a testnet timestamper but you are working on livenet.  You might have messed up your configs.

**Comment by pxrunes** [comment]
oh yea, that is clearly an issue with this contract. Strange anyway that it is parsed correctly in my wallet.
