### ISSUE TITLE
Transition bot does not answer

### ISSUE THREAD

**Issue by kaipoethkow** [byteball/byteball#193]
After the bot telling me
```
[...] In this case, let me know your Bitcoin address first.
```
and me pasting the bitcoin address, there is no answer anymore.

This was tested on Linux amd64 with versions 1.9.2 and 1.9.3.

**Comment by sabotagebeats** [comment]
I have had this issue on android as well.

**Comment by tonyofbyteball** [comment]
fixed, try again
