### ISSUE TITLE
wrong amount given bij transition bot

### ISSUE THREAD

**Issue by Lazuruus** [byteball/byteball#196]
Hi,

After the first two times I did transactions to the connected wallet, the right amount was given by the transition bot on the Byteballwallet. Then I increased the connected wallet once more and again the transition bot gave the correct value of it.

A day later, I asked the balance again and it gave the exact previous amount of it and not the increased one. For example: first it was 0.2, it went up to 0.4. The transition bot first said 0.2 and afterwards 0.4, but the day after it stated 0.2 again. 

I was thinking it had something to do with the hardfork and all, but Im not sure. Somebody who can help or has the same problem?

Thanks in advance,

**Comment by tonyofbyteball** [comment]
Closed as not related to the wallet, see #helpdesk on slack.
