### ISSUE TITLE
major bug: password saved in plain text linux

### ISSUE THREAD

**Issue by pwpwpwpw** [byteball/byteball#201]
I noticed with linux mint 18.2, I assume all ubuntu and other linux distros do the same as well. I tested light and full clients too, 2 things happen, first of all the password that you request is remembered and automatically filled in when you start the client and it is saved in plain text at ~/.config/byteball/default/Login Data
text inside is:
"chrome-extension://ppgbkonninhcodjcnbpghnagfadnfjck/public/index.htmlchrome-extension://ppgbkonninhcodjcnbpghnagfadnfjck/public/index.htmlpasswordchrome-extension://ppgbkonninhcodjcnbpghnagfadnfjck/"

BTW the seed in linux is not saved in plain text, only the password.

Not 100% on OSX but thedavidmeister confirmed in slack that OSX saves passwords the same way.

I tested the exact same steps, install light and full client, request pass, exit, search for pass in all files as text and windows 7 x64 does not save the pass or the seed. I don't use win 10 but someone can test the same thing. So this is a bug in the linux/osx, using latest clients version 1.10.

**Comment by tonyofbyteball** [comment]
related https://github.com/nwjs/nw.js/issues/5944

**Comment by tonyofbyteball** [comment]
Fixed in 1.10.1 by reverting to an older nwjs.

**Comment by pwpwpwpw** [comment]
Thanks, tried and tested, it all works fine in linux mint, bug is resolved.
