### ISSUE TITLE
Client Saved Passphrase as Plaintext to Disk

### ISSUE THREAD

**Issue by toothpasterocket** [byteball/byteball#219]
I'm using 'v1.10.0 light' on Ubuntu 16.04 and the client saved the wallet password to the following file as plaintext:

/home/%user%/.config/byteball/Default/Login Data

It also presented the password pre-filled into the startup / send prompts. 

After deleting the 'Login Data' file, the client is no longer pre-filling the password. I haven't been able to replicate the issue.

It looks like this is rendering in Chrome and the pre-fill presented a similar interface to Chrome's password "manager". How can I be sure the interface doesn't trying to save the passphrase to disk again?

**Comment by tonyofbyteball** [comment]
duplicate https://github.com/byteball/byteball/issues/201
