### ISSUE TITLE
Node crashes while it tries to sync

### ISSUE THREAD

**Issue by polpolrene** [byteball/byteball#222]
I've tried versions 1.10 and 1.10 for Windows. I use Win10/64. The node starts to "sync" and a 0% shows up. Even before the node goes to 1% it crashes and the program closes itself. When I enable TOR this problem is gone, but the syncing never goes above 0% so no gain here as well.

I've tried to connect to byteball.org/bb as the program defaulted to some French server (some .fr) address. Still no luck here. For some reason the program closes itself while it tries to connect to some server somewhere.

**Comment by iPaltus** [comment]
I have the same - 1.10.1 full wallet crashes when trying to sync first time. Light wallet worked.
Windows 10 x64 with all updates, enough RAM, CPU and HDD.
Wallet and Windows show no error messages, wallet just closes. Is there a way to collect debug information?

**Comment by iPaltus** [comment]
Wallet 1.10.1 win32 version crashes too at initial sync.
Full wallet on my other PC with win64 started to sync several days ago with 1.9.3 version. After updating to 1.10.1 sync continues without crash.
So I noticed that crash occurs only at clean wallet installation with initial sync.

**Comment by polpolrene** [comment]
Thanks for the reply. If people want to replicate this bug, remove all appdata (on windows use %appdata%) and do a clean install starting from zero. The bugs shows up on different versions and on both 32-bit and 64-bit.

**Comment by johnnymakebelieve** [comment]
I have exactly the same problem with 1.10.1 full version for the Mac. Syncing doesn't work - with or without TOR, it doesn't matter. Changing the hub also haven't any effect.

**Comment by tonyofbyteball** [comment]
duplicate https://github.com/byteball/byteball/issues/220

**Comment by iensu69** [comment]
same problem here. on win 2000 r2

**Comment by tonyofbyteball** [comment]
fixed in 1.11.0
