### ISSUE TITLE
Byteball crashed on OSX after launch with the following error message

### ISSUE THREAD

**Issue by barryhi** [byteball/byteball#225]
Error message "ncaught exception: Error: Error: SQLITE_CORRUPT: database disk image is malformed PRAGMA journal_mode=WAL"

Please help, thanks

Barry

**Comment by tonyofbyteball** [comment]
the database is corrupt, you have to revert to a backup.

**Comment by shinelikeamillion** [comment]
seam question 
i created a multiple address wallet
i selected install full wallet (haven't backup)
and it start syncing
it syncing very slow (about several days)
and today when came home
the application (on mac os x) crashed
very time i open it
it shows this dialog
![image](https://user-images.githubusercontent.com/9711578/34950600-8ef3e574-fa4e-11e7-829b-1da73d0e38f5.png)

the application works fine on my mobile phone.
how can i resolve this problem?
sorry for my poor english
and I will appreciate your help with this situation.
