### ISSUE TITLE
Byteball hangs with black window on Linux (Ubuntu 16.04) after start

### ISSUE THREAD

**Issue by SteffenIvanhoe** [byteball/byteball#231]
I had a problem with the wallet. It showed an error and aborted. This did not allow me to try the backup. Therefore I deleted '~/.config/byteball' to enforce a fresh start. Now the wallet only shows a black window and hangs. Absolutely no robustness here. I have no idea how to get it re-used???

**Comment by tonyofbyteball** [comment]
what error did it show?

**Comment by SteffenIvanhoe** [comment]
Sorry, happened to long ago. I can't remember. If you could avoid the black windows blocking everything that would be great. Probably the second window shows the error message. But because it is black and takes no input there is no chance to continue.

**Comment by tonyofbyteball** [comment]
the last time i've seen a black window on ubuntu, it as on a virtual machine (some graphics issues).  Otherwise, try to reinstall the wallet.

**Comment by SteffenIvanhoe** [comment]
Yes, Ubuntu was running in VirtualBox, as I always run it. Usually there are no graphics issues. Re-install did not work. Got access to bytes with the backup in a Windows wallet installation. But lost all blackbytes. Gave up on Byteball.
