### ISSUE TITLE
sync slower than real time from September 17th

### ISSUE THREAD

**Issue by iensu69** [byteball/byteball#238]
sync slower than real time from September 17th
full wallet, running on Win 7 64 bit

**Comment by tonyofbyteball** [comment]
did you happen to send any transactions from unsynced wallet?

**Comment by iensu69** [comment]
if I remember correctly, I've tried to create a transaction after the wallet was in that state of syncing slower than real time.
I'm running the full wallet 24/7 on a VPS and the sync is at 9/19/17 3:16 PM now

**Comment by tonyofbyteball** [comment]
that transaction could be one reason for the slow down.  The sync will be slow until the date of this tx is reached.

**Comment by iensu69** [comment]
sync at 9/21/17 11:40 AM now - still slower sync than real time
checked my chat history at slack -> the transaction I tried to create must have been on September 19th.

**Comment by raschle** [comment]
Is there a fix for this? I have the same problem and need to get the GBB out of this wallet.

**Comment by Sorrow2** [comment]
i started syncing before distribution on 3rd of November.
I was at 11 october. Now i am at 21 of october. And i have computer turned on close to 24/7.
Indeed very slow syncing now.

**Comment by iensu69** [comment]
solved with one of the last releases
