### ISSUE TITLE
iOS Wallet

### ISSUE THREAD

**Issue by Aragonite** [byteball/byteball#295]
The last version of the iOS wallet provided was at 1.10.1.    Would it be possible to provide the xcodeproj file at version 2.1? 

I attempted to use the source code to compile the app with ionic cordova, but running the app failed. 

The process created a xcodeproj file, but when the app is run on the iPhone, it goes into infinite loop - with the debug error " xxx Byteball[xxx:xxxxxx] Error: ("line":20215, "column":25, "sourceURL":"file:///var/containers/Bundle/Application/.../Byteball.app/www/partialClient.js")"

To compile the app I used the following commands:  
1.  **npm install**     -  from the Byteball source code directory (which installs most deps)
2. **make ios-debug**   - which creates the Xcodeproj files in a directory called byteballbuilds
3. From Xcode, enter my Team profile, then compile and run, with my iPhone as the target. 

PS:  I did downgrade my Cordova to version 6 prior step 1, as instructed by the readme file.

**Comment by Aragonite** [comment]
Any help available?

**Comment by hk78** [comment]
Why is there no ongoing development? Would it be quicker/better to give incentives/rewards to developers for the iOS App to be coded? Or give it to contractors?

**Comment by gutenye** [comment]
@Aragonite You forget to run `bower install`

**Comment by tonyofbyteball** [comment]
Now in the App Store https://itunes.apple.com/us/app/byteball/id1147137332?ls=1&mt=8
