### ISSUE TITLE
Request specific amound/share address produces a bad address

### ISSUE THREAD

**Issue by fxbonnet** [byteball/byteball#299]
To reproduce the issue on Android:

- Receive
- Request a specific ammount
- Generate QR code
- Share address
- Select mail

The address looks like:
{{protocol}}:MZ4GUQC7WUKZKKLGAS3H3FSDKLHI7HFO?amount=1000000000

{{protocol}} should be replaced by byteball

**Comment by tonyofbyteball** [comment]
fixed, thanks for reporting!
