### ISSUE TITLE
Wrong private profile inserted into the chat when multiple are available

### ISSUE THREAD

**Issue by pmiklos** [byteball/byteball#301]
When the wallet has multiple private profiles, on a profile request always the same private profile is inserted no matter which one the user selects from the drop down.

Steps to reproduce:
* create two single address wallets on your device
* attest each to create two private profiles
* insert private profile into a chat eg. via a profile request: select the second item from the drop down list
* send profile to the chat bot and observe the other profile that was displayed first in the drop down list is sent

The only way to send the correct profile it to select the wallet that has the attested profile. In that case that one is gonna be the first item in the drop down and so will be sent in the chat bot.

It gets confusing if you have more (eg. non-profile) wallets, then it seems quite random which profile is picked on a profile request.

**Comment by tonyofbyteball** [comment]
The bug affected only android and was fixed some time ago, sorry for late reply.
