### ISSUE TITLE
KB/MB/GB units are rounded to the nearest integer

### ISSUE THREAD

**Issue by TheRealCryptKeeper** [byteball/byteball#35]
The higher units aren't shown with decimal point. The values are shown as integers, which are rounded, e.g. '1 GB' will be shown for a balance of 500 MB (if you have set GB unit).
This issue is the same for Bytes and Blackbytes.

**Comment by xJeneKx** [comment]
Fixed https://github.com/byteball/byteball/commit/2b4d75e7b56830aa813af1cef79bbeee6f78673c

**Comment by tonyofbyteball** [comment]
Will be included in 1.3
