### ISSUE TITLE
new added address does not display in addressbook

### ISSUE THREAD

**Issue by PeterDu0404** [byteball/byteball#354]
in android(pc is ok), when add a new address in addressbook,and re-enter the addressbook,the added address does not display in addressbook,it seems that is a ui bug? can fix it?

**Comment by tonyofbyteball** [comment]
I tried in iOS (should not be different from android) and it appears in address book.  Please could you specify the exact steps to reproduce.

**Comment by PeterDu0404** [comment]
i just fixed this issue by adding $timeout(function () { $scope.$digest(); } in $scope.listEntries function,it should refresh ui after bingding the data.
