### ISSUE TITLE
Downloadlinks might be broken

### ISSUE THREAD

**Issue by FalkF** [byteball/byteball#358]
Somehow the download from https://byteball.org/#download seems to be strangely messed up.
Firefox simply refuses to start the download (source file not readable) and Chrome finishes the download but fails to open the file.

**Comment by tonyofbyteball** [comment]
I failed to reproduce this behavior.  Network connection, firewalls, antiviruses? any specific steps?

**Comment by FalkF** [comment]
I just retried it and could not reproduce it either, so I am closing the issue.
Might have been something that was specific to me an my roommates connection on that day or a github hickup 🤷‍♂️
