### ISSUE TITLE
Transactions on light wallet do not confirm

### ISSUE THREAD

**Issue by TheRealCryptKeeper** [byteball/byteball#36]
Sometimes a tx on a light wallet does not confirm, waited about one hour.
After clicking on the balance, it confirmed at once.
I've already seen this behavior with byte transactions, today a user reported it for a blackbyte tx.
Wallet version of the user is recent (1.2.0).

**Comment by tonyofbyteball** [comment]
Desktop or mobile?
How likely is it that the connection was temporarily interrupted?

**Comment by TheRealCryptKeeper** [comment]
Android app. Not very likely that the connection was interrupted, my wifi is very reliable.

**Comment by tonyofbyteball** [comment]
It's interrupted every time the phone goes to sleep, almost sure thing.

**Comment by tonyofbyteball** [comment]
I failed to reproduce the issue for byte transactions, the phone wallet behaved as expected both when it was allowed to sleep and when I kept the screen on.  Need steps to reproduce.

**Comment by tonyofbyteball** [comment]
For blackbytes, status changes automatically since 1.8.5
