### ISSUE TITLE
Windows wallet defaults to program folder for backup

### ISSUE THREAD

**Issue by TheRealCryptKeeper** [byteball/byteball#361]
If you do a full wallet backup on windows, the wallet brings up a save file dialog which defaults to the program folder of the Byteball wallet (usually sth like ‘c:\program files\byteball’). Starting with windows vista, write access to the program folder is restricted and requires administrative rights. So the attempt to save the backup fails and an error dialog is shown with the option to save in the user’s home folder.

I think this behavior is irritating for new users and should be changed to default the backup folder to the user’s home folder right from the start.

**Comment by tonyofbyteball** [comment]
@kakysha

**Comment by kakysha** [comment]
https://github.com/kakysha/byteball/commit/9d9f28e2e222506428b59ef3e13dc6ed7a2d92f0

**Comment by tonyofbyteball** [comment]
Fixed by the above commit.
