### ISSUE TITLE
Mobile wallets don't recognize any qr codes

### ISSUE THREAD

**Issue by TheRealCryptKeeper** [byteball/byteball#363]
Tried with v2.4.0 on iOS and Android: qr codes are not recognized anymore!
Test strings: 
byteball:VBKAASZUIZ3EQ23YJJDLDW7JDGMJDGZ5?amount=10000000
byteball:VBKAASZUIZ3EQ23YJJDLDW7JDGMJDGZ5
Byteball:VBKAASZUIZ3EQ23YJJDLDW7JDGMJDGZ5

**Comment by tarmo888** [comment]
Can confirm, on Android 8.1.0 with v2.4.0, amount is loaded, but address is disabled and not possible to send, tried with other address too.
![address-mising](https://user-images.githubusercontent.com/732356/43045241-c04c8e70-8dbd-11e8-953c-cbcc38cb54cb.png)

On Windows 10, v2.4.1 works fine.

**Comment by tarmo888** [comment]
Looks like it is fixed on v2.4.2 for Android.

**Comment by TheRealCryptKeeper** [comment]
Yes, fixed for Android and iOS with v2.4.2
