### ISSUE TITLE
Full Wallet v2.6.0 (win 64bit) exception after an attempt to Full Backup

### ISSUE THREAD

**Issue by tm3558** [byteball/byteball#391]
Byteball full wallet for windows 64-bit throws an exception after pressing "Full backup" in Global Preferences (I have password **set**):

> An exception occurred: SyntaxError: Error parsing C:\Program Files (x86)\Byteball\node_modules\zip\package.json: Unexpected token  in JSON at position 0; cause: \<section ui-view="main" ng-class="{ 'main': index.hasProfile }" ng-show="!index.$state.includes('correspondentDevices')" class="ng-scope"\>
> OK
> Back Full backup
>      Exporting...
>  Failed to export
> SET UP A PASSWORD

**Comment by tarmo888** [comment]
I can confirm that I have the same issue, looks like corrupted `zip` node module is included with installer.

**Comment by tonyofbyteball** [comment]
Correct, the zip module was corrupt. I replaced the windows binaries without changing the version number, please download and install again.

**Comment by tm3558** [comment]
Full Backup now works OK.
