### ISSUE TITLE
Unable to remove device from chat

### ISSUE THREAD

**Issue by bonustrack** [byteball/byteball#395]
When i click for remove device in the chat the garbage icon does not appear on each contacts, for some reason few of the contact does not have icon see example: 

![screenshot_20181021-141443_byteball](https://user-images.githubusercontent.com/16245250/47264217-3a706a80-d53c-11e8-919e-d95966f4473d.jpg)

In my contact list i got 4 of them enable to delete.

**Comment by tarmo888** [comment]
These bots that you have had smart-contracts with cannot be removed.
It would need to implement some kind of hide & mute functionality for those bots.

**Comment by bonustrack** [comment]
Ho yes that make sense! Good catch, thank you @tarmo888. I'm closing this issue then as it's not a real issue.
