### ISSUE TITLE
Decimal point for GB and GBB is same as thousands separator

### ISSUE THREAD

**Issue by TheRealCryptKeeper** [byteball/byteball#41]
Both the decimal point and the thousands separator are shown as a dot ('.').
It doesn't matter if I switch the wallet language from english to german (germany has a dot as thousands separator and a comma as decimal point), both languages use dots.

Tested with wallet version 1.3.0 on win 10 64bit.

**Comment by xJeneKx** [comment]
Thanks, fixed. https://github.com/byteball/byteball/pull/43

**Comment by tonyofbyteball** [comment]
released in 1.4
