### ISSUE TITLE
Add 'address insert' menu for every wallet in chats

### ISSUE THREAD

**Issue by TheRealCryptKeeper** [byteball/byteball#45]
If you've linked with a bot, like the exchange bot, and you need to enter your byte address for linking, it's not obvious from which wallet this address is from (if you have more than one wallet on your device).
It happened to me for both the transition bot and the exchange bot, that bytes were sent into the wrong wallet. I think there must be more guidance for the user how he can do this. It's not even the last wallet you were looking at before you go into the chat, how I assumed. Currently I see the only way to be sure to use the address from the right wallet is to copy one from the 'receive' tab but that's too complicated for the average user.
My suggestion is to add a menu entry into the three dots menu '...' for each wallet which contains the name of the wallet:

- insert my address (Personal Wallet)
- insert my address (Trading Wallet)
- request payment (Personal Wallet)
- request payment (Trading Wallet)

You'll get the idea.

**Comment by tonyofbyteball** [comment]
I assigned different colors to different wallets, so I know which wallet is current.

I don't think the menu would look nice when all wallets are listed (then you also have to duplicate the "Request payment" menu item) but adding some indication of the *current* wallet (apart from color) would be helpful indeed.

**Comment by TheRealCryptKeeper** [comment]
Thanks for the info, the colors for my two wallets were quite similar, so I've missed this. Now I see that the 'arrow button' right to the chat's input field corresponds to the color of the wallet, which is nice.
But fiddling around with this, it's even more obvious that the wallet switch isn't working correctly. It seems not to be sufficient to be in the wallet for a switch, sometimes it works, sometimes not. Maybe this switch function needs an overhaul.
