### ISSUE TITLE
'Paired Devices' lags during synchronisation

### ISSUE THREAD

**Issue by TheRealCryptKeeper** [byteball/byteball#46]
If I open my wallet and go to 'Paired Devices' while it's still syncing, the list is empty.
On my system (core i-7 with win 10) it takes around 13 seconds to show up. Would be good to have something like a progress indicator while it's not available (some users aren't as patient as I am).

This issue is only seen on the full wallet, not on the light wallet (tested on android).

**Comment by tonyofbyteball** [comment]
@kakysha

**Comment by kakysha** [comment]
@TheRealCryptKeeper tried to replay the bug myself, under heavy disk load and while being synced, Paired Devices list shows up pretty quick, worst case was ~2 seconds. Was you doing something heave in terms of disk usage when this bug occurred?

**Comment by TheRealCryptKeeper** [comment]
No. I'm using an old core i7 but with a new samsung ssd, normally I have
no such issues. 

I have two subwallets and a password, if that matters.

**Comment by pmiklos** [comment]
I encountered with the same yesterday. The paired device list was empty for a long time. At first I thought it was because I switched to another hub, but then I found out the hub should not matter. I have i5.

**Comment by tonyofbyteball** [comment]
Due to optimizations in 1.4, the lagging should become extremely rare.
