### ISSUE TITLE
Not possible to enter fractions of a unit in 'Request Payment'

### ISSUE THREAD

**Issue by TheRealCryptKeeper** [byteball/byteball#52]
It's not possible to enter fraction of a unit, e.g. 0.5 GB or 0.5 GBB, if you use the 'Request Payment' button in chat. 
I've attached a screenshot.
![bbrequestamountbug](https://cloud.githubusercontent.com/assets/25538715/23720336/bed197de-043e-11e7-9cc2-9fcf6c35d885.PNG)

**Comment by tonyofbyteball** [comment]
fixed
