### ISSUE TITLE
Can't send too little BB, like 1BB or 1KBB

### ISSUE THREAD

**Issue by jtomtan** [byteball/byteball#54]
When I tried to send 1BB or 1KBB to someone else, the client shows the following error message: 
Could not send payment: all paying addresses are unfunded in asset

When I tried to send 1MBB, it works!

So first issue is that is 1BB or 1KBB allowed to be sent, or they must be more? If it is allowed, it should be a bug. Otherwise the error message should be adjusted to give more friendly information!

**Comment by tonyofbyteball** [comment]
Most likely, your balance was still unconfirmed when you were making your first attempts to send blackbytes.  Please make sure your entire balance is confirmed, then try again.
