### ISSUE TITLE
no checksum file for downloads

### ISSUE THREAD

**Issue by dindinw** [byteball/byteball#67]
Hi, @tonyofbyteball , looks there is no any checksum file for the byteball offical downloads. For some people in China who gets trouble to download from the github due to the network issue, they have to share binary files from chat chanel or other unoffical sources. I think the checksum files might be useful for them to verify their downloads.
Thanks
--Alex

**Comment by tonyofbyteball** [comment]
The binaries are signed (except linux). Isn't it a more user friendly way to verify integrity?

**Comment by dindinw** [comment]
Hi, guy, It's cool
$ codesign -dv --verbose=4 /Volumes/Byteball-osx64/Byteball.app
Executable=/Volumes/Byteball-osx64/Byteball.app/Contents/MacOS/nwjs
Identifier=com.nw-builder.byteball
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=279 flags=0x0(none) hashes=3+3 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha1=e26102cad1ddb1cc5b03e2f3521350f6bfbe85d4
CandidateCDHash sha256=d0584571aa5c0ffeb35f71a2975a5e6e89ea7482
Hash choices=sha1,sha256
CDHash=d0584571aa5c0ffeb35f71a2975a5e6e89ea7482
Signature size=8925
Authority=Developer ID Application: Matrix Platform LLC (96S944NY84)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Mar 19, 2017, 12:26:59 AM
Info.plist entries=30
TeamIdentifier=96S944NY84
Sealed Resources version=2 rules=12 files=6867
Internal requirements count=1 size=184
I think few people know that 👍
