### ISSUE TITLE
Releases need signatures

### ISSUE THREAD

**Issue by oriolpont** [byteball/byteball#70]
If not, $11M could be lost because of a hacked password

**Comment by tonyofbyteball** [comment]
The binaries are signed (see https://github.com/byteball/byteball/issues/67) and the signatures are supposed to be automatically checked by the OS.

**Comment by oriolpont** [comment]
That is clearly not sufficient for a cryptocurrency project. Please provide PGP signatures as it is customary in that space.

**Comment by JulianTosh** [comment]
Tony, 

Please reconsider creating PGP keys, uploading the pubkey to a key server like pgp.mit.edu, and then including detached signatures of the OS packages in each release.

To sign the packages, simply run "gpg -b byteball-linux64.zip", for example, and results in a .sig file. This is how BitPay releases CoPay and offers a 2nd layer of protection over the code releases.

Thank you for your contributions to this project.
