### ISSUE TITLE
support single address wallet

### ISSUE THREAD

**Issue by dindinw** [byteball/byteball#71]
Hi, @tonyofbyteball , is possible to migrate the copay 2.0 feature to support single address as an advanced option?
see https://github.com/bitpay/copay/blob/master/src/js/services/profileService.js#L392
It's useful sometimes to keep using the single address for both receiving payments and sending tx change.
Thanks
--Alex

**Comment by dindinw** [comment]
https://github.com/bitpay/bitcore-wallet-service/blob/master/lib/server.js#L898
and 
https://github.com/bitpay/bitcore-wallet-service/blob/master/lib/server.js#L1913

**Comment by errge** [comment]
Hey, I think I have implemented this feature with my pull request here: https://github.com/byteball/byteball/pull/179

**Comment by tonyofbyteball** [comment]
done in 1.11.0

**Comment by errge** [comment]
@tonyofbyteball Thanks, awesome!  Already using it!
