### ISSUE TITLE
[LINUX] Full Backup Issue 

### ISSUE THREAD

**Issue by Nickardo** [byteball/byteball#72]
Byteball 1.7, Linux Fedora.

Without Compression:
After I click the "Export" button, a "Exporting..." message appears.
After waiting for some minutes the app closes automatically without warning.

With Compression:
Uncaught exception: RangeError: Array buffer allocation failed.  And the app closes.

**Comment by Nickardo** [comment]
@enkaptor in Slack reported the issue

**Comment by TheRealCryptKeeper** [comment]
I have it on Windows 10 with 1.7.0 and 1.7.1:
backup says 'Failed to export' in red, regardless whether compression is on or off.

**Comment by D3m0nKingx** [comment]
I"m running 1.7.0 on Linux Ubuntu 64-bit, and did a full backup yesterday without issue.

**Comment by TheRealCryptKeeper** [comment]
How many subwallets do you have? I have 3, maybe that's relevant somehow.

**Comment by D3m0nKingx** [comment]
Just 1, but I've had 3 just to test, didn't test a full backup before with more than 1.  I'm not sure they're "sub"-wallets tho, like one being "under" another, but rather separate of each other.

**Comment by tonyofbyteball** [comment]
@D3m0nKingx are you running full or light version?  I suspect it is related to the size of the database.

**Comment by boestin** [comment]
Same issue here on windows 10 64bit.   Wallet is still syncing though.

**Comment by tonyofbyteball** [comment]
We are working on the issue, please backup by copying files before we release a fix.

**Comment by tonyofbyteball** [comment]
Full backup works again since 1.8.3

**Comment by boestin** [comment]
Nice work Tony!
