### ISSUE TITLE
error:socket closed 

### ISSUE THREAD

**Issue by no4long** [byteball/byteball#74]
when i send my byteball, it shows "socket closed".
when i open the chat and link my bitcoin it shows“socket closed” too……

I want to unistall the client and recover from my seed，but it says，i must install the full wallet。
what should i do？
env:
- mac
- v1.7.0

**Comment by tonyofbyteball** [comment]
Please try the following:
* start the wallet
* right click and Inspect **Background** Page
* reproduce the error
* send me the entire contents of the console log on the background page

**Comment by hmmmshaihulud** [comment]
I'm having this issue as well? Please, i've tried everything, including the slack help. 
![bb](https://cloud.githubusercontent.com/assets/29172057/26759946/f53cebb2-48c1-11e7-9200-20377db637b3.jpg)

**Comment by tonyofbyteball** [comment]
Check your firewall.  It blocked connections for other users.

**Comment by hmmmshaihulud** [comment]
I've shut down all firewalls, and the error is still present.  I reopened after shutting down all firewall processes, including windows firewall. Do i need to reinstall with them down? How do i save the information from this install? Thank you for your help Tony, Jim

**Comment by tonyofbyteball** [comment]
I don't think a reinstall would help.
What is your hub?

**Comment by TSavo** [comment]
I'm having an identical issue now. No firewall. Hub is the default: byteball.org/bb

**Comment by TSavo** [comment]
Seeing this a lot in the logs: error from server wss://byteball.org/bb: Error: Socket Closed

**Comment by TSavo** [comment]
[bb log.zip](https://github.com/byteball/byteball/files/1063557/bb.log.zip)

**Comment by githubUser92** [comment]
I have the same problem because I had activated Tor my solution was to disabled it

**Comment by D3m0nKingx** [comment]
I'm using linux ubuntu 16.04 and running the Wallet (v 1.9.0 light) throught Tor without a problem, but in linux you have to have Tor daemon running in the background which is listening on your localhost port for your wallet to connect through, Did you actually have tor running on the system?

See https://www.torproject.org/docs/tor-doc-osx.html.en

**Comment by tonyofbyteball** [comment]
Summing up:
* check TOR
* check firewall
* you might be blocked by the hub for 1 hour after sending something invalid.  Wait or change to another hub
