### ISSUE TITLE
Uncaught exception: Error: know bad...

### ISSUE THREAD

**Issue by flintknap** [byteball/byteball#78]
Wallet installed on Windows 10.  Receiving the following error about 30 seconds after opening.
Uncaught exception: Error: known bad
{string A}= 
{string A} = 
last ball unit
{string B}
is not stable in view of your parents
{string C}

**Comment by flintknap** [comment]
Uninstall and re-installation resolved issue.

**Comment by tonyofbyteball** [comment]
Fixed in 1.8
