### ISSUE TITLE
Multisig/Co-sign wallets - delete from one, remains in other

### ISSUE THREAD

**Issue by maff1989** [byteball/byteball#93]
I have 2 Byteball nodes configured on 2 different devices. We'll call them Device 1 (full client) and Device 2 (light client)

Set up a multi-device wallet on Device 1 and set Device 2 as a cosigner.

I deleted the wallet from Device 2, and the wallet remained on Device 1. There was no prompt received on Device 1 stating the wallet had been deleted from Device 2.

I would think this should require all-device approval before any member of the wallet can delete it?

**Comment by mitchellurgero** [comment]
Have you tried turning it on and off again?

**Comment by tonyofbyteball** [comment]
We cannot require approval from cosigners because some them might be already non-existent.  You have to manually delete wallets from all devices.
