### ISSUE TITLE
sync issue (large outgoing traffic, full CPU)

### ISSUE THREAD

**Issue by Quark-Fusion** [byteball/byteball#94]
A lot messages of this type in log:
\Byteball\node_modules\byteballcore\network.js:94 SENDING ["justsaying",{"subject":"result","body":{"unit":"

[different units here]

","result":"error","error":"error on (indirect) parent unit Gr8quwNcf9BodoQmC1YJCdAov/VKlKqnABWLt+L4wGM=: unit Gr8quwNcf9BodoQmC1YJCdAov/VKlKqnABWLt+L4wGM= does not exist"}}] to wss://byteball.org/bb

**Comment by Quark-Fusion** [comment]
same problem on another pc

**Comment by umatej** [comment]
Sync doesnt work or doesnt complete and its super slow. Also wrong balance in wallet after receiving GB. I received less than i sent?!  v1.8.1 and also in 1.8.2 ...

**Comment by tonyofbyteball** [comment]
These error messages are harmless, how long do they continue?

**Comment by Quark-Fusion** [comment]
sync doesn't start wth 1.8.2, same large outgoing traffic, they are countless and continue like forever, now it is "9uSm8Md2I5oE0kaM7dV0FTgRcUwhJCFhGAF3+Lz5S9Q="

**Comment by umatej** [comment]
I made manual backup and deleted byteball and all the data. After that i installed latest version and it synced in 1 day and i got all the funds in the wallet except blackbytes.

**Comment by tonyofbyteball** [comment]
sync issues resolved in 1.8.5

**Comment by albertolive** [comment]
Hi,

I have downloaded the full wallet three months ago and it never fully sync. Now I have the main page:

![image](https://user-images.githubusercontent.com/1182864/29173290-1f3d5d10-7de3-11e7-8e99-ab2ae65c893c.png)

The folder of byteball in my application support is 3,12 GB big.

How can I fix that?
