### ISSUE TITLE
Wallet not running after updating to 1.8.2 on OSX

### ISSUE THREAD

**Issue by Kingsize1** [byteball/byteball#98]
Hello There!

After updating to 1.8.2 on OSX I get the following error message:

uncaught exception: Error: Error: SQLITE_ERROR: duplicate column name: my_record_pref ALTER TABLE correspondent_devices ADD COLUMN my_record_pref INTEGER DEFAULT 1

What can be done to fix this issue?

Best regards,

Kingsize1

**Comment by tonyofbyteball** [comment]
Did I reply to you by email?

**Comment by Kingsize1** [comment]
Yes! You did reply to me! Thank you very much! It is working again!

Best regards,

Karl.
